name       : php
version    : 7.0.1
release    : 13
source     :
    - http://php.net/distributions/php-7.0.1.tar.xz : 84fcb8b9c61f70db802d3b6636c6ba602470a375e593375c0c744483aa0c0357
license    : PHP License
summary    : PHP is a popular general-purpose scripting language that is especially suited to web development.
description: |
    PHP is a popular general-purpose scripting language that is especially suited to web development.
builddeps  :
  - pkgconfig(enchant)
  - pkgconfig(freetype2)
  - pkgconfig(gdlib)
  - pkgconfig(icu-i18n)
  - pkgconfig(libcurl)
  - pkgconfig(libexif)
  - pkgconfig(libpng)
  - pkgconfig(libpq)
  - pkgconfig(libxml-2.0)
  - pkgconfig(libxslt)
  - pkgconfig(libzip)
  - pkgconfig(openssl)
  - pkgconfig(sqlite3)
  - pkgconfig(zlib)
  - bzip2
  - gettext-devel
  - gmp-devel
  - mcrypt
  - libjpeg-turbo-devel
  - libmcrypt-devel
  - libmhash-devel
  - libtool
  - pam-devel
setup      : |
    cp $pkgfiles/php.ini-production ./

    # Purge imap test of success

    sed -i '271,277d' ext/imap/config.m4
    sed -i '42,45d' ext/phar/Makefile.frag

    # Swap out /var/run for /run

    sed -i 's:/var/run:/run:' ext/fileinfo/tests/magic
    sed -i 's:/var/run:/run:' sapi/phpdbg/phpdbg.init.d

    libtoolize --force
    aclocal
    autoconf

    %configure --prefix=/usr --disable-static --with-config-file-path=/etc/php/ --bindir=/usr/bin/ --mandir=/usr/share/man \
         --disable-cgi \
         --enable-calendar=shared \
         --enable-exif=shared \
         --enable-fpm \
         --enable-ftp=shared \
         --enable-intl=shared \
         --enable-mbstring \
         --enable-opcache \
         --enable-phar \
         --enable-posix=shared \
         --enable-shmop=shared \
         --enable-soap=shared \
         --enable-libxml=shared \
         --enable-zip=shared \
         --mandir=/usr/share/man \
         --sysconfdir=/etc/php \
         --with-bz2=shared \
         --with-config-file-path=/etc/php \
         --with-config-file-scan-dir=/etc/php/conf.d \
         --with-curl=shared \
         --with-enchant=shared \
         --with-freetype-dir=/usr \
         --with-gd=shared \
         --with-gettext=shared \
         --with-gmp=shared \
         --with-iconv=shared \
         --with-icu-dir=/usr \
         --with-jpeg-dir=/usr \
         --with-libdir=lib64 \
         --with-libzip \
         --with-mcrypt=shared \
         --with-mhash \
         --with-openssl \
         --with-openssl-dir=/usr/bin \
         --with-pdo-pgsql=shared \
         --with-pdo-sqlite=shared \
         --with-pgsql=shared \
         --with-png-dir=/usr \
         --with-sqlite3=shared \
         --with-xsl=/usr \
         --with-zlib \
         --without-pear
make      : |
    %make
install      : |
    make INSTALL_ROOT=%installroot% install
    rm -rf %installroot%/usr/lib64/build
    install $pkgfiles/php.ini-production %installroot%/etc/php/php.ini
    rm -rf %installroot%/usr/include/php/include
    rm -rf %installroot%/var
