name       : php
version    : 7.4.24
release    : 88
source     :
    - https://www.php.net/distributions/php-7.4.24.tar.xz : ff7658ee2f6d8af05b48c21146af5f502e121def4e76e862df5ec9fa06e98734
license    : PHP-3.01
component  : programming
summary    : PHP is a popular general-purpose scripting language that is especially suited to web development
description: |
    PHP is a popular general-purpose scripting language that is especially suited to web development.
networking : yes # For CURL tests
builddeps  :
    - pkgconfig(oniguruma)
    - pkgconfig(enchant)
    - pkgconfig(gdlib)
    - pkgconfig(icu-i18n)
    - pkgconfig(libargon2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libpq)
    - pkgconfig(libsasl2)
    - pkgconfig(libsodium)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(libzip)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - bzip2-devel
    - gettext-devel
    - imap-devel
    - net-snmp-devel
    - openldap-devel
    - tidy-html5-devel
patterns   :
    - devel :
        - /usr/bin/phpize
        - /usr/lib64/build
setup      : |
    export EXTENSION_DIR=%libdir%/php/modules/
    cp $pkgfiles/php.ini-production ./

    # Swap out /var/run for /run
    sed -i 's:/var/run:/run:' ext/fileinfo/tests/magic
    sed -i 's:/var/run:/run:' sapi/phpdbg/phpdbg.init.d

    rm -rf aclocal.m4 autom4te.cache config.cache configure main/php_config.h.in
    autoconf -f
    autoheader

    %configure --prefix=/usr --disable-static --bindir=/usr/bin/ \
         --enable-bcmath \
         --enable-calendar=shared \
         --enable-exif=shared \
         --enable-fpm \
         --enable-ftp=shared \
         --enable-gd=shared \
         --enable-intl=shared \
         --enable-mbstring \
         --enable-pcntl \
         --enable-posix=shared \
         --enable-shmop=shared \
         --enable-soap=shared \
         --enable-sockets=shared \
         --mandir=/usr/share/man \
         --sysconfdir=/etc/php \
         --with-bz2=shared \
         --with-config-file-path=/etc/php \
         --with-config-file-scan-dir=/etc/php/conf.d \
         --with-curl=shared \
         --with-enchant=shared \
         --with-external-gd \
         --with-external-pcre \
         --with-fpm-user=phpfpm \
         --with-fpm-group=phpfpm \
         --with-fpm-systemd \
         --with-gettext=shared \
         --with-gmp=shared \
         --with-iconv=shared \
         --with-imap=shared \
         --with-imap-ssl \
         --with-ldap=shared \
         --with-ldap-sasl \
         --with-libdir=lib64 \
         --with-mhash \
         --with-mysqli=shared,mysqlnd \
         --with-openssl \
         --with-password-argon2 \
         --with-pdo-mysql=shared,mysqlnd \
         --with-pdo-pgsql=shared \
         --with-pdo-sqlite=shared \
         --with-pgsql=shared \
         --with-readline \
         --with-snmp=shared \
         --with-sodium=shared \
         --with-sqlite3=shared \
         --with-tidy=shared \
         --with-xsl \
         --with-zip=shared \
         --with-zlib
build      : |
    export EXTENSION_DIR=%libdir%/php/modules/
    %make
profile    : |
    export NO_INTERACTION=1 REPORT_EXIT_STATUS=1 SKIP_IO_CAPTURE_TESTS SKIP_IO_CAPTURE_TESTS=1
    unset TZ LANG LC_ALL
    %make test || :
install    : |
    export EXTENSION_DIR=%libdir%/php/modules/
    make INSTALL_ROOT=%installroot% install
    # Cleanup
    rm -f $installdir/etc/php/php-fpm.d/www.conf.default
    rm -rf $installdir/usr/lib64/php/modules/*.a
    rm -rf $installdir/usr/include/php/include
    rm -rf %installroot%/var
    # Install configs
    install $pkgfiles/php.ini-production $installdir/etc/php/php.ini
    install $pkgfiles/www.conf $installdir/etc/php/php-fpm.d/www.conf
    mv $installdir/etc/php/php-fpm.conf.default $installdir/etc/php/php-fpm.conf
    # Setup service and tmpfiles
    sed 's:${exec_prefix}:/usr:g' -i sapi/fpm/php-fpm.service
    install -Dm00644 sapi/fpm/php-fpm.service $installdir/%libdir%/systemd/system/php-fpm.service
    install -Dm00644 $pkgfiles/phpfpm.sysusers $installdir%libdir%/sysusers.d/phpfpm.conf
    install -Dm00644 $pkgfiles/phpfpm.tmpfiles $installdir/%libdir%/tmpfiles.d/php-fpm.conf
